global:
  checkNewVersion: false
  sendAnonymousUsage: false
metrics:
  # @doc https://doc.traefik.io/traefik/observability/metrics/prometheus/
  prometheus:
    entryPoint: metrics
    buckets:
    - 0.005
    - 0.01
    - 0.025
    - 0.05
    - 0.1
    - 0.25
    - 0.3
    - 0.5
    - 1.0
    - 2.5
    - 5.0
    - 10.0
log:
  level: 'INFO'
accessLog:
  filePath: '/dev/stdout'
api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ':8081'
  metrics:
    address: ":8082"
providers:
  file:
    directory: '/etc/traefik'
    watch: false
http:
  routers:
    mirror-router:
      rule: Query(`mirror=1`)
      service: mirrored-api
      middlewares:
      - appendHeader
  middlewares:
    appendHeader:
      headers:
        customRequestHeaders:
          X-Mirrored: "true"
  services:
    mirrored-api:
      mirroring:
        service: backend1
        mirrors:
        - name: backend2
          percent: 100
    backend1:
      loadBalancer:
        servers:
        - url: 'http://backend1:8001/'
    backend2:
      loadBalancer:
        servers:
        - url: 'http://backend2:8002/'
