entryPoints:
  web:
    address: ':80'
providers:
  file:
    directory: /etc/traefik
    watch: false
http:
  routers:
    app-router:
      rule: Query(`mirror=1`)
      service: mirrored-api
  services:
    mirrored-api:
      mirroring:
        service: backend1
        mirrors:
        - name: backend2
          percent: 100
    backend1:
      loadBalancer:
        servers:
        - url: 'http://backend1:8001/'
    backend2:
      loadBalancer:
        servers:
        - url: 'http://backend2:8002/'
