// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend/services/v1/hello.proto

package backend_services_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb2e5bedbde1b42, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

type HelloResponse struct {
	// Types that are valid to be assigned to Result:
	//	*HelloResponse_Success_
	//	*HelloResponse_Failure_
	Result               isHelloResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb2e5bedbde1b42, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

type isHelloResponse_Result interface {
	isHelloResponse_Result()
}

type HelloResponse_Success_ struct {
	Success *HelloResponse_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type HelloResponse_Failure_ struct {
	Failure *HelloResponse_Failure `protobuf:"bytes,2,opt,name=failure,proto3,oneof"`
}

func (*HelloResponse_Success_) isHelloResponse_Result() {}

func (*HelloResponse_Failure_) isHelloResponse_Result() {}

func (m *HelloResponse) GetResult() isHelloResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *HelloResponse) GetSuccess() *HelloResponse_Success {
	if x, ok := m.GetResult().(*HelloResponse_Success_); ok {
		return x.Success
	}
	return nil
}

func (m *HelloResponse) GetFailure() *HelloResponse_Failure {
	if x, ok := m.GetResult().(*HelloResponse_Failure_); ok {
		return x.Failure
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*HelloResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*HelloResponse_Success_)(nil),
		(*HelloResponse_Failure_)(nil),
	}
}

type HelloResponse_Success struct {
	StatusCode           string   `protobuf:"bytes,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse_Success) Reset()         { *m = HelloResponse_Success{} }
func (m *HelloResponse_Success) String() string { return proto.CompactTextString(m) }
func (*HelloResponse_Success) ProtoMessage()    {}
func (*HelloResponse_Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb2e5bedbde1b42, []int{1, 0}
}

func (m *HelloResponse_Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse_Success.Unmarshal(m, b)
}
func (m *HelloResponse_Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse_Success.Marshal(b, m, deterministic)
}
func (m *HelloResponse_Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse_Success.Merge(m, src)
}
func (m *HelloResponse_Success) XXX_Size() int {
	return xxx_messageInfo_HelloResponse_Success.Size(m)
}
func (m *HelloResponse_Success) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse_Success.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse_Success proto.InternalMessageInfo

func (m *HelloResponse_Success) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

type HelloResponse_Failure struct {
	ErrorCode            string   `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse_Failure) Reset()         { *m = HelloResponse_Failure{} }
func (m *HelloResponse_Failure) String() string { return proto.CompactTextString(m) }
func (*HelloResponse_Failure) ProtoMessage()    {}
func (*HelloResponse_Failure) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cb2e5bedbde1b42, []int{1, 1}
}

func (m *HelloResponse_Failure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse_Failure.Unmarshal(m, b)
}
func (m *HelloResponse_Failure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse_Failure.Marshal(b, m, deterministic)
}
func (m *HelloResponse_Failure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse_Failure.Merge(m, src)
}
func (m *HelloResponse_Failure) XXX_Size() int {
	return xxx_messageInfo_HelloResponse_Failure.Size(m)
}
func (m *HelloResponse_Failure) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse_Failure.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse_Failure proto.InternalMessageInfo

func (m *HelloResponse_Failure) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *HelloResponse_Failure) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "backend.services.v1.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "backend.services.v1.HelloResponse")
	proto.RegisterType((*HelloResponse_Success)(nil), "backend.services.v1.HelloResponse.Success")
	proto.RegisterType((*HelloResponse_Failure)(nil), "backend.services.v1.HelloResponse.Failure")
}

func init() { proto.RegisterFile("backend/services/v1/hello.proto", fileDescriptor_9cb2e5bedbde1b42) }

var fileDescriptor_9cb2e5bedbde1b42 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xff, 0x46, 0xfa, 0x1b, 0x32, 0x69, 0x91, 0x30, 0x9b, 0x2a, 0x02, 0x15, 0xc2, 0x06,
	0x75, 0xe1, 0xa8, 0xe5, 0x06, 0x20, 0x55, 0xdd, 0x74, 0x93, 0x1e, 0x00, 0xb9, 0xc9, 0x10, 0x22,
	0x42, 0x9c, 0x7a, 0x9c, 0x1c, 0x80, 0x2b, 0x70, 0x05, 0x6e, 0xc4, 0x15, 0x38, 0x08, 0x8a, 0xed,
	0x22, 0x90, 0x10, 0xb0, 0xcc, 0xcb, 0x7b, 0x9f, 0xdf, 0xcc, 0xc0, 0x74, 0x2b, 0xb2, 0x07, 0xac,
	0xf3, 0x84, 0x50, 0x75, 0x65, 0x86, 0x94, 0x74, 0xf3, 0xe4, 0x1e, 0xab, 0x4a, 0xf2, 0x46, 0x49,
	0x2d, 0xd9, 0xb1, 0x33, 0xf0, 0xbd, 0x81, 0x77, 0xf3, 0xe8, 0xa4, 0x90, 0xb2, 0xa8, 0x30, 0x11,
	0x4d, 0x99, 0x88, 0xba, 0x96, 0x5a, 0xe8, 0x52, 0xd6, 0x64, 0x23, 0xf1, 0x21, 0x8c, 0x56, 0x3d,
	0x21, 0xc5, 0x5d, 0x8b, 0xa4, 0xe3, 0x17, 0x0f, 0xc6, 0x4e, 0xa0, 0x46, 0xd6, 0x84, 0x6c, 0x09,
	0x3e, 0xb5, 0x59, 0x86, 0x44, 0x93, 0xc1, 0xd9, 0xe0, 0x32, 0x5c, 0xcc, 0xf8, 0x37, 0xcf, 0xf0,
	0x2f, 0x21, 0xbe, 0xb1, 0x89, 0xd5, 0xbf, 0x74, 0x1f, 0xee, 0x39, 0x77, 0xa2, 0xac, 0x5a, 0x85,
	0x13, 0xef, 0xcf, 0x9c, 0xa5, 0x4d, 0xf4, 0x1c, 0x17, 0x8e, 0x66, 0xe0, 0x3b, 0x3a, 0x9b, 0x42,
	0x48, 0x5a, 0xe8, 0x96, 0x6e, 0x33, 0x99, 0xa3, 0xa9, 0x17, 0xa4, 0x60, 0xa5, 0x1b, 0x99, 0x63,
	0xb4, 0x06, 0xdf, 0x11, 0xd8, 0x29, 0x00, 0x2a, 0x25, 0xd5, 0x67, 0x6b, 0x60, 0x94, 0xde, 0xc9,
	0x2e, 0x60, 0x6c, 0x7f, 0x3f, 0x22, 0x91, 0x28, 0x6c, 0xc7, 0x20, 0x1d, 0x19, 0x71, 0x6d, 0xb5,
	0xeb, 0x03, 0x18, 0x2a, 0xa4, 0xb6, 0xd2, 0x8b, 0x9d, 0x5b, 0xdb, 0xc6, 0x36, 0x67, 0x02, 0xfe,
	0x9b, 0x6f, 0x76, 0xfe, 0xd3, 0x50, 0x66, 0xc5, 0x51, 0xfc, 0xfb, 0xdc, 0xf1, 0xd1, 0xd3, 0xeb,
	0xdb, 0xb3, 0x17, 0xb2, 0xe0, 0xe3, 0xc4, 0xdb, 0xa1, 0x39, 0xd8, 0xd5, 0x7b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf1, 0x7e, 0x1a, 0xf2, 0x06, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/backend.services.v1.HelloService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedHelloServiceServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServiceServer struct {
}

func (*UnimplementedHelloServiceServer) Hello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backend.services.v1.HelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backend.services.v1.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend/services/v1/hello.proto",
}
