apiVersion: v1
kind: Service
metadata:
  name: api-app
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-app
          image: kenju/ruby-rails-api:latest
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
