version: 2
updates:
- package-ecosystem: bundler
  directory: "/containers/ruby-sinatra-api"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  reviewers:
  - kenju
  labels:
  - dependencies
- package-ecosystem: bundler
  directory: "/containers/ruby-rails-api"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  reviewers:
  - kenju
  labels:
  - dependencies
- package-ecosystem: gomod
  directory: "/containers/go-grpc-api"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  reviewers:
  - kenju
  labels:
  - dependencies
