version: '3.7'
services:

  backend1:
    image: kenju/go-http-api:latest
    expose:
      - '8080'

  backend2:
    image: kenju/go-http-api:latest
    expose:
      - '8080'

  nginx:
    build:
      context: './nginx'
    ports:
      - '80:80'
    links:
      - 'backend1'
      - 'backend2'
    volumes:
      - ./nginx/conf:/etc/nginx:ro
