kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: traefik-ingress-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-ingress-router
subjects:
  - kind: ServiceAccount
    name: traefik-ingress-router
    namespace: traefik-ingress-router
