---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: latency-check-easy
  namespace: default
spec:
  circuitBreaker:
    expression: LatencyAtQuantileMS(50.0) > 100

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: latency-check-harsh
  namespace: default
spec:
  circuitBreaker:
    # NOTE: deliberately return error
    expression: LatencyAtQuantileMS(50.0) > 0

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: modify-header
  namespace: default
spec:
  headers:
    customRequestHeaders:
      X-Script-Name: "test"
    customResponseHeaders:
      X-Custom-Response-Header: "value"
