global:
  scrape_interval: '15s'
  evaluation_interval: '15s'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'fluentd-logging'
    kubernetes_sd_configs:
      - role: 'pod'
    relabel_configs:
      - source_labels:
          - '__meta_kubernetes_namespace'
          - '__meta_kubernetes_pod_container_name'
          - '__meta_kubernetes_pod_container_port_name'
        regex: 'default;fluentd;http'
        action: 'keep'
