version: "3.7"
services:
  app:
    image: solsson/http-echo
    networks:
      envoymesh:
        aliases:
          - app
    expose:
      - "80"
    ports:
      - "8080:80"
  envoy:
    build:
      context: './envoy'
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
    environment:
      - "ENVOY_UID=0" # https://github.com/envoyproxy/envoy/pull/11323
  log-service:
    build:
      context: './log-service'
    networks:
      - envoymesh
    expose:
      - "4567"
    ports:
      - "4567:4567"

networks:
  envoymesh: {}
