version: '3.7'
services:

  backend1:
    image: kenju/go-http-api:latest
    expose:
    - '8001'
    networks:
    - mesh
    ports:
    - '8001:8001'
    environment:
    - ADDR=:8001

  backend2:
    image: kenju/go-http-api:latest
    expose:
    - '8002'
    networks:
    - mesh
    ports:
    - '8002:8002'
    environment:
    - ADDR=:8002

  backend3:
    image: kenju/go-http-api:latest
    expose:
    - '8003'
    networks:
    - mesh
    ports:
    - '8003:8003'
    environment:
    - ADDR=:8003

  traefik:
    build:
      context: './traefik'
    networks:
    - mesh
    ports:
    - "8080:8080" # Dashboard https://doc.traefik.io/traefik/operations/dashboard/
    - "8081:8081" # Web Entrypoint
    - "8082:8082" # Metrics Entrypoint

networks:
  mesh:
