name: Push ruby-sinatra-api to hub.docker.com

on:
  push:
    branches:
      - master
    paths:
      - 'containers/ruby-sinatra-api/**'

env:
  WORKDIR: containers/ruby-sinatra-api
  DOCKER_IMAGE_NAME: ruby-sinatra-api

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to docker hub
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ${{ env.WORKDIR }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tag_with_ref: true
          tag_with_sha: true
