name: Push go-grpc-api to hub.docker.com

on:
  push:
    branches:
      - master
    paths:
      - 'containers/go-grpc-api/**'
      - 'containers/protobuf-definitions/**'

env:
  WORKDIR: containers/go-grpc-api
  DOCKER_IMAGE_NAME: go-grpc-api

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to docker hub
        if: success()
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ${{ env.WORKDIR }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}
          tag_with_ref: true
          tag_with_sha: true
