name: CI go-grpc-api
on:
  push:
    branches:
      - master
    paths:
      - 'containers/go-grpc-api/**'
  pull_request:
    paths:
      - 'containers/go-grpc-api/**'
jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          working-directory: containers/go-grpc-api
          only-new-issues: true
